### ISSUE TITLE
Development environment

### ISSUE THREAD

**Issue by mmarkelov** [mmarkelov/jest-playwright#1]
- eslint
- prettier
- travis
- tests

**Comment by mxschmitt** [comment]
Maybe instead of TravisCI directly GitHub Actions?

**Comment by mmarkelov** [comment]
@mxschmitt thank you for suggestion! I should take a look on it.

**Comment by mxschmitt** [comment]
@mmarkelov I can set it up for you if you want :)

**Comment by mmarkelov** [comment]
@mxschmitt sure! It will be perfect!

**Comment by mxschmitt** [comment]
Seems like we can close this issue @mmarkelov

**Comment by mmarkelov** [comment]
@mxschmitt yeah! I suppose so. But we really need to think about tests
