### ISSUE TITLE
Only the first test case respects setting jest.setTimeout()

### ISSUE THREAD

**Issue by thernstig** [mmarkelov/jest-playwright#100]
For some reason, the second (and third, and fourth and so on) test case does not respect what is set with `jest.setTimeout()`. Only the first test case does.

I've got a Jest config like this:

```javascript
module.exports = {
  testSequencer: './tests/e2e/util/jestSequencer.js',
  projects: [
    {
      displayName: 'E2E',
      rootDir: 'tests/e2e',
      preset: 'jest-playwright-preset',
      runner: '<rootDir>/util/serialJestRunner.js',
      setupFilesAfterEnv: [
        '<rootDir>/jest.setup.js',
        '<rootDir>/util/registerAllureReporter',
      ],
      transformIgnorePatterns: [
        '/node_modules/(?!(query-selector-shadow-dom)/)',
      ],
    },
  ],
};
```

`jest.setup.js` sets `jest.setTimeout(5000);`.

When running two test cases where I on purpose delay them (to replicate this), this is what I receive:

```sh
 FAIL   E2E  tests/e2e/suite/login/login.e2e.test.js (21.387s)
  \u25cf Login page \u203a has a title

    : Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:

      22 |   });
      23 | 
    > 24 |   it('has a title', async () => {
         |   ^
      25 |     await sleep(11000);
      26 |     const title = await page.title();
      27 |     expect(title).toBe('Login');

      at new Spec (../../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (suite/login/login.e2e.test.js:24:3)

 FAIL   E2E  tests/e2e/suite/login/foo.e2e.test.js (15.55s)
  \u25cf Console

    console.error node_modules/jest-jasmine2/build/jasmine/Env.js:248
      Unhandled error
    console.error node_modules/jest-jasmine2/build/jasmine/Env.js:249
      Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
          at CRSession.send (/home/userA/code/projectA/node_modules/playwright-core/lib/chromium/crConnection.js:121:19)
          at CRSession.<anonymous> (/home/userA/code/projectA/node_modules/playwright-core/lib/helper.js:84:31)
          at CRExecutionContext.evaluate (/home/userA/code/projectA/node_modules/playwright-core/lib/chromium/crExecutionContext.js:70:83)
        -- ASYNC --
          at Frame.<anonymous> (/home/userA/code/projectA/node_modules/playwright-core/lib/helper.js:63:23)
          at Page.title (/home/userA/code/projectA/node_modules/playwright-core/lib/page.js:285:33)
          at Page.title (/home/userA/code/projectA/node_modules/playwright-core/lib/helper.js:84:31)
          at Object.<anonymous> (/home/userA/code/projectA/tests/e2e/suite/login/login.e2e.test.js:26:30)

  \u25cf Login page \u203a has a title

    Timeout - Async callback was not invoked within the 10000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 10000ms timeout specified by jest.setTimeout.
```

Notice the **5000ms** timeout (which is what I configured) vs the **10000ms**, where I have no idea where that comes from.

It can be reproduced by having two tests files with this:

```javascript
const { promisify } = require('util');

const sleep = promisify(setTimeout);

beforeAll(async () => {
  await page.goto(`http://example.com/`);
}, 10000);

it('sleep', async () => {
  await sleep(11000);
  expect(true).toBe(true);
});
```

**Comment by thernstig** [comment]
Ok, updates. I can see the above failure (in the post just above this) happening even if I visually look at it via headless=false and seeing that all three test cases passes i.e. they all execute and close the browser like they should.

This error has most likely existed for a few versions. I've seen colleagues get this on their computer and I just thought they had not installed the npm packages or something properly, but it seems this is a real and serious bug due to that the test cases become unstable.

If we can somehow deduct where the **10000ms** comes from that gets printed, then we might have a lead. It is not something I set in my codebase either through `jest.setTimeout()` nor the config `testTimeout`.

**Comment by mmarkelov** [comment]
@thernstig hm..
As I know `jest.setTimeout(5000)` will set the timeout globally per suite. And for example:
```js
it('sleep', async () => {
  ...
}, 10000)
``` 
will set the timeout for specified test. 

So 10000 can came from this case.

Not sure about `beforeAll`, cause for me:
```js
const { promisify } = require('util');

const sleep = promisify(setTimeout);

beforeAll(async () => {
    await page.goto(`http://example.com/`);
}, 10000);

it('sleep', async () => {
    await sleep(11000);
    expect(true).toBe(true);
});
```

will throw 
```
 Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:
```

**Comment by thernstig** [comment]
Hmm I know I have this that runs before each test.

```javascript
beforeAll(async () => {
  await page.goto(`${global.TEST_URL}/login.html`);
}, 10000);
```

But, that part is in a beforeAll and not in each test case, which the timeouts shows above. Also, I can clearly see the test cases passing when I view it in headful mode. There is something really fishy here. Could it be a Jest bug?

**Comment by thernstig** [comment]
I wonder if jest-circus solves this hmm.

**Comment by thernstig** [comment]
I noticed a lot of issues on jest on timesout in async `beforeAll()`/`beforeEach()` etc. The timeouts in those ended up running test cases anyway looking the the test cases timed out. For example: https://github.com/facebook/jest/issues/8442, https://github.com/facebook/jest/issues/9685, https://github.com/facebook/jest/issues/8688, https://github.com/facebook/jest/pull/8654 and many more. 

I will close this. I am fairly certain this is not a jest-playwright fault. Sorry for taking your time.
