### ISSUE TITLE
jest-dev-server and wait-on

### ISSUE THREAD

**Issue by thernstig** [mmarkelov/jest-playwright#101]
The current jest-dev-server in this package-lock.json (https://github.com/mmarkelov/jest-playwright/blob/master/package-lock.json) is:

```json
    "jest-dev-server": {
      "version": "4.4.0",
      "resolved": "https://registry.npmjs.org/jest-dev-server/-/jest-dev-server-4.4.0.tgz",
      "integrity": "sha512-STEHJ3iPSC8HbrQ3TME0ozGX2KT28lbT4XopPxUm2WimsX3fcB3YOptRh12YphQisMhfqNSNTZUmWyT3HEXS2A==",
      "requires": {
        "chalk": "^3.0.0",
        "cwd": "^0.10.0",
        "find-process": "^1.4.3",
        "prompts": "^2.3.0",
        "spawnd": "^4.4.0",
        "tree-kill": "^1.2.2",
        "wait-on": "^3.3.0"
      }
    },
```

`jest-dev-server` version `4.4.0` (https://github.com/smooth-code/jest-puppeteer/blob/master/packages/jest-dev-server/package.json) has this in its `package.json`:

```json
  "dependencies": {
    "chalk": "^3.0.0",
    "cwd": "^0.10.0",
    "find-process": "^1.4.3",
    "prompts": "^2.3.0",
    "spawnd": "^4.4.0",
    "tree-kill": "^1.2.2",
    "wait-on": "^4.0.0"
  }
```

How is it that `wait-on` then is only at version `3.3.0` above? I need to use features in `4.0.0`.

**Comment by mxschmitt** [comment]
Since it's not bundled into the package ([ref](https://unpkg.com/jest-dev-server@4.4.0/lib/global.js)) you could probably use the [Yarn resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) feature or their not existing [NPM equivalent](https://stackoverflow.com/questions/52416312/npm-equivalent-of-yarn-resolutions).

**Comment by thernstig** [comment]
This might be out of my ballpark. I do not understand the https://unpkg.com/jest-dev-server@4.4.0/lib/global.js. I thought that when a dependency of a dependency lists a specific version, that one would be installed. We are unfortunately not using Yarn nor want to bring in such a small package as npm-force-resolutions (preferably not at least). Is there another way around this, or that you in jest-playwright in any way can force 4.4.0?

**Comment by mxschmitt** [comment]
> This might be out of my ballpark. I do not understand the [unpkg.com/jest-dev-server@4.4.0/lib/global.js](https://unpkg.com/jest-dev-server@4.4.0/lib/global.js). I thought that when a dependency of a dependency lists a specific version, that one would be installed. We are unfortunately not using Yarn nor want to bring in such a small package as npm-force-resolutions (preferably not at least). Is there another way around this, or that you in jest-playwright in any way can force ~4.0.0?

maybe just try: `npm install wait-on` to install the latest version of it. Otherwise we would need to create a upstream issue on jest-dev-server side.

**Comment by mmarkelov** [comment]
@thernstig I'm not sure that it is **jest-playwright** issue. I suppose that ```npm install wait-on``` will help. It's better to open issue for **jest-dev-server**

**Comment by thernstig** [comment]
You both might be right here 😄 I am going to open an issue on `jest-dev-server` to see what they say.

**Comment by thernstig** [comment]
I think you might have to fork that package because there is not a ton of activity on jest-puppeteer.
