### ISSUE TITLE
Testing jest-playwright

### ISSUE THREAD

**Issue by mmarkelov** [mmarkelov/jest-playwright#17]
https://github.com/mmarkelov/jest-playwright/issues/1#issuecomment-583255213

**Comment by mxschmitt** [comment]
I can start with that later. Thought first about a stub test to launch the browsers, open a html file and check if the heading is equal to an expected one.

**Comment by mxschmitt** [comment]
Seems to be also done right? @mmarkelov 
Or do you want to cover some other functionalities?

**Comment by mmarkelov** [comment]
@mxschmitt I suppose we can close it, cause I opened this issue for creation just starter tests
