### ISSUE TITLE
Add configuration option to run all browsers in parallel

### ISSUE THREAD

**Issue by arjun27** [mmarkelov/jest-playwright#19]
It would be great to be able to run tests in all browsers with just one command.

**Comment by aesyondu** [comment]
Or let's say for example I want to test:
browsers: ["firefox", "chromium", "webkit"]
devices: ["iPhone X", "iPad Pro 11", "MacBook Pro 13-inch"]

```javascript
for (let browserType of browsers) {
  const browser = await playwright[browserType].launch()

  for (let device of devices) {
    // loop through each device and browser for each test
  }
}
```

How would I go about doing that?

**Comment by mmarkelov** [comment]
@aesyondu with version **0.0.7** you can check Readme for running for multiple browsers:
https://github.com/mmarkelov/jest-playwright#unstable-and-experimental-api

I suppose I can also add support for **devices**, but before it I need to test current behavior for **browsers**

**Comment by aesyondu** [comment]
Just tested it and it works great. I observed on non-headless that it 1. opened chromium, 2. completed all the tests, 3. opened webkit, 4. completed all the tests, etc. I'm thinking of a way to make it execute all browsers at the same time, just to shorten the test time.

**Comment by mmarkelov** [comment]
@aesyondu you should try it with `--parallel` option:
```jest-playwright --parallel```

**Comment by aesyondu** [comment]
Thanks man! It does execute at the same time. Didn't realize I misspelled `paralel`. That was stupid.

**Comment by aesyondu** [comment]
I'm getting a warning of some sort, is it safe to ignore?:

<img width="402" alt="image" src="https://user-images.githubusercontent.com/57334943/74512610-a225a280-4f43-11ea-8b85-a9a18c7921a9.png">

<details>
<summary>
app.spec.js
</summary>

```javascript
const path = require("path")
const { saveScreenshot } = require("./helpers")

const fileName = path.basename(__filename).split(".")[0]
const baseUrl = "http://localhost:3000";

describe("Landing Page", () => {
  beforeAll(async () => {
    await page.goto(baseUrl)
  }, 30000)

  afterAll(async () => {
    await page.close()
  })

  it("1. should show the landing page", async () => {
    await page.evaluate(() => {
      const html = document.documentElement
      const body = document.body

      window.scrollTo(0, Math.max(
        body.scrollHeight,
        body.offsetHeight,
        html.scrollHeight,
        html.offsetHeight,
        html.clientHeight,
      ))
    })

    await saveScreenshot(fileName, page)

    const landingText = await page.$eval('"Watch Video"', (node) => node.textContent)
    expect(landingText).toContain("Watch Video")
  })
})
```
</details>


<details>
<summary>
stdout
</summary>
<pre>
> my-project@1.0.0 test:playwright-parallel /path/to/my-project
> jest-playwright --parallel "test/e2e/app.spec.js"

(node:35988) ExperimentalWarning: queueMicrotask() is experimental.
(node:35987) ExperimentalWarning: queueMicrotask() is experimental.
(node:35989) ExperimentalWarning: queueMicrotask() is experimental.
PASS test/e2e/app.spec.js (6.274s)
  Landing Page
    ✓ 1. should show the landing page (707ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        6.364s, estimated 13s
Ran all test suites matching /test\/e2e\/app.spec.js/i.
PASS test/e2e/app.spec.js (8.065s)
  Landing Page
    ✓ 1. should show the landing page (1462ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        8.157s, estimated 13s
Ran all test suites matching /test\/e2e\/app.spec.js/i.
PASS test/e2e/app.spec.js (11.973s)
  Landing Page
    ✓ 1. should show the landing page (364ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        12.085s, estimated 13s
Ran all test suites matching /test\/e2e\/app.spec.js/i.
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
</pre>
</details>

**Comment by mmarkelov** [comment]
@aesyondu this is not critical, but I suppose something is wrong with **teardown** function, I'll check it out

**Comment by aesyondu** [comment]
Warning disappeared when I removed "firefox". When I added it back it reappeared.

**Comment by mmarkelov** [comment]
> Warning disappeared when I removed "firefox". When I added it back it reappeared.

@aesyondu seems like something is wrong with **firefox**

**Comment by mmarkelov** [comment]
I think we can close it, I just added support to run tests for multiple devices in **0.0.13**
