### ISSUE TITLE
jestPlaywright is not defined

### ISSUE THREAD

**Issue by johnnybravo81** [mmarkelov/jest-playwright#21]
After following the basic setup, I am running into following issue:

![image](https://user-images.githubusercontent.com/6212638/74103364-81d79b80-4b71-11ea-92b3-b325db374d26.png)

Environment
node -v 12.15.0
Windows 10

**Comment by mxschmitt** [comment]
Which version of `jest-playwright` have you installed? It was added in version `0.0.6`.

**Comment by johnnybravo81** [comment]
> Which version of `jest-playwright` have you installed? It was added in version `0.0.6`.

Indeed bumping the version of `jest-playwright` from `0.0.5` to `0.0.6` solved the issue. Thanks much for the help!
