### ISSUE TITLE
jest-dev-server support

### ISSUE THREAD

**Issue by thernstig** [mmarkelov/jest-playwright#29]
Contemplating to move to Playwright, but due to dependency to jest-puppeteer I need to make sure this plugin will work just as well. I could not find in the documentation if https://github.com/smooth-code/jest-puppeteer#start-a-server is supported. Could this be added and if it already is, the README updated with information about it.

**Comment by mmarkelov** [comment]
@thernstig there is no **jest-dev-server** support right now. I'll take it in progress. I suppose it wouldn't take much time to support [jest-dev-server](https://github.com/smooth-code/jest-puppeteer/tree/master/packages/jest-dev-server)

**Comment by thernstig** [comment]
@mmarkelov stellar work 🥇
