### ISSUE TITLE
[BUG] page.route not working properly

### ISSUE THREAD

**Issue by aesyondu** [mmarkelov/jest-playwright#38]
**Context:**
- Jest-Playwright Version: 0.0.9
- Playwright Version: 0.11.1
- Operating System: Mac OS X 10.14.6
- Extra: node@11.15.0 npm@6.7.0

**Code Snippet**

```javascript
    /** works **/
    // const { chromium } = require("playwright")
    // const mybrowser = await chromium.launch()
    // const mycontext = await mybrowser.newContext()
    // const mypage = await mycontext.newPage()
    // await mypage.route(/\.(png|jpeg|jpg)$/, request => request.abort());
    // await mypage.goto(baseUrl)

    /** doesn't work, throws error **/
    await page.route(/\.(png|jpeg|jpg)$/, request => request.abort());
    await page.goto(baseUrl)
```

**Describe the bug**

`page.route` throws the error below, works fine when instantiating playwright manually:

```
  console.error node_modules/jest-jasmine2/build/jasmine/Env.js:248
    Unhandled error

  console.error node_modules/jest-jasmine2/build/jasmine/Env.js:249
    Error: url parameter should be string, RegExp or function
        at Object.assert (/Users/aes/projects/amber/node_modules/playwright-core/lib/helper.js:196:15)
        at Object.urlMatches (/Users/aes/projects/amber/node_modules/playwright-core/lib/platform.js:206:14)
        at Page._requestStarted (/Users/aes/projects/amber/node_modules/playwright-core/lib/page.js:315:26)
        at FrameManager.requestStarted (/Users/aes/projects/amber/node_modules/playwright-core/lib/frames.js:145:24)
        at CRNetworkManager._onRequest (/Users/aes/projects/amber/node_modules/playwright-core/lib/chromium/crNetworkManager.js:169:34)
        at CRNetworkManager._onRequestPaused (/Users/aes/projects/amber/node_modules/playwright-core/lib/chromium/crNetworkManager.js:144:18)
        at CRSession.emit (events.js:193:13)
        at Promise.resolve.then (/Users/aes/projects/amber/node_modules/playwright-core/lib/chromium/crConnection.js:135:47)
```

**Comment by mmarkelov** [comment]
@aesyondu hm! This is strange, I'm not sure what can be wrong with it. 
It seems be OK when I'm using string with it:
```js
    it('this is the second test', async () => {
        await page.route('**/*.{png,jpg,jpeg}', request => request.abort());
        await page.goto('https://example.com')
    })
```

Looks like ```instanceof RegExp``` for passed regexp return **false**.
I'll try to find out why it is happend

**Comment by aesyondu** [comment]
How is this possible :o

<img width="183" alt="image" src="https://user-images.githubusercontent.com/57334943/74653893-1c645a00-51c4-11ea-9433-d7d9f896d9ab.png">

<img width="766" alt="image" src="https://user-images.githubusercontent.com/57334943/74653929-2d14d000-51c4-11ea-84a1-b4fca607002a.png">

**Comment by aesyondu** [comment]
Umm, what...

<img width="286" alt="image" src="https://user-images.githubusercontent.com/57334943/74654055-6cdbb780-51c4-11ea-8bf4-e278aaa2513f.png">

**Comment by aesyondu** [comment]
Using:
```javascript
    const { chromium } = require("playwright")
    const mybrowser = await chromium.launch()
    const mycontext = await mybrowser.newContext()
    const mypage = await mycontext.newPage()
    await mypage.route(/\.(png|jpeg|jpg)$/, request => request.abort());
    await mypage.goto(baseUrl)
```

<img width="773" alt="image" src="https://user-images.githubusercontent.com/57334943/74654429-381c3000-51c5-11ea-8c72-441603495376.png">

**Comment by mmarkelov** [comment]
@aesyondu I suppose it came from **jest**, but actually I'm not sure. It's very confusing

**Comment by aesyondu** [comment]
Gottem... hahaha. I will try to make a pull request to playwright.

```javascript
  if (match instanceof RegExp || match.constructor.name == "RegExp")
    return match.test(urlString);
```

https://stackoverflow.com/questions/4339288/typeof-for-regexp#comment4724685_4339350

<img width="693" alt="image" src="https://user-images.githubusercontent.com/57334943/74654913-52a2d900-51c6-11ea-8840-b35b2a9c4e42.png">

**Comment by mxschmitt** [comment]
Closed since the upstream PR looks like it was merged.
