### ISSUE TITLE
Missing TypeScript typings for global page

### ISSUE THREAD

**Issue by tkrotoff** [mmarkelov/jest-playwright#41]
In my source code I've added types/jest-playwright-preset.d.ts:

```TypeScript
import { Page } from 'playwright';

declare global {
  const page: Page;
}
```

Allows `page` to be typed:

```JavaScript
describe('Google', () => {
  beforeAll(async () => {
    await page.goto('https://whatismybrowser.com/')
  })
  ...
```

More or less related to #26

**Comment by mxschmitt** [comment]
By using the latest version `0.0.11` we now have types attached. So you can use either in your `tsconfig.json`.
```
    "types": [
      "jest-playwright-preset"
    ]
```

or via the Triple-Slash Directives:
```
// eslint-disable-next-line spaced-comment
/// <reference types="jest-playwright-preset" />
```
The ESLint ignore rule is there, because without, it will convert `///` into `// /`.

**Comment by tkrotoff** [comment]
❤️
