### ISSUE TITLE
How to pass arguments to the browser executable?

### ISSUE THREAD

**Issue by tkrotoff** [mmarkelov/jest-playwright#42]
How to pass arguments to the browser executable?

Use case:
- https://github.com/microsoft/playwright/issues/1062
- https://github.com/arjun27/playwright-github-actions/blob/2770e149bdd75408203aa2b6590e11dafec6fdc3/test-project/index.js#L19

For GitHub Actions to work with Playwright, we need to pass `--no-sandbox` to chromium

I think the arguments should be passed somewhere here: https://github.com/mmarkelov/jest-playwright/blob/v0.0.10/src/PlaywrightEnvironment.js#L48

**Comment by mmarkelov** [comment]
@tkrotoff you can pass it with **jest-playwright.config.js**:
```js
module.exports = {
	launchBrowserApp: {
		args: ['--no-sandbox']
	}
}
```

**Comment by arjun27** [comment]
Note that WebKit will crash when launched with `no-sandbox`, which is a valid arg for Chromium only. 

For now, I recommend using `process.env.BROWSER === ‘chromium’ ? ['--no-sandbox'] : []`

Follow this as we look for a better fix: https://github.com/microsoft/playwright/issues/1063
