### ISSUE TITLE
Collaborate

### ISSUE THREAD

**Issue by jperl** [mmarkelov/jest-playwright#43]
@celeryclub asked about using [jest-playwright with qawolf](https://github.com/qawolf/qawolf/issues/444), which I thought was a great idea!

There is some overlap and it would be great for us to be able to use jest-playwright under the hood. I am curious if you are planning to maintain this library and if you are you open to collaborators?

**Comment by jperl** [comment]
We would want to do things like separate out our video recording to a plugin so you could install jest-playwright-video and it will record your browsers in CI. This might require some changes to jest-playwright.

**Comment by mmarkelov** [comment]
@jperl yeah! That's sounds great!

**Comment by mxschmitt** [comment]
Let's maybe use some way of synchronous communication like Telegram or Slack?
Seems to be more efficient to collaborate over in my mind.
What do you think?

**Comment by mmarkelov** [comment]
@mxschmitt lgtm! I think this is a good idea

**Comment by mxschmitt** [comment]
@mmarkelov afaik most communities are switching over to Discord, so if you don't mind I would simply create a server there.

**Comment by mmarkelov** [comment]
@mxschmitt we should wait @jperl  thoughts about it

**Comment by jperl** [comment]
I have been using Gitter for QA Wolf because embed it on our docs site which lowers the barrier for people to get help. That being said, it doesn’t really matter to me.

**Comment by mxschmitt** [comment]
Probably something like the new discussion feature is something what we need: https://github.com/zeit/next.js/discussions
hmm. Maybe I can talk to somebody of GitHub that they can enable that for us too if you want.

**Comment by jperl** [comment]
I think a chat is probably better. Discord or Slack or Gitter, doesn't matter to me. My vote is Discord since you brought it up, and they have audio support as well.

**Comment by jperl** [comment]
I went ahead and created a discord (will make you both admins upon joining) -- just to get started. We can change if you prefer. https://discord.gg/duyWaa

**Comment by jperl** [comment]
Ok so I created and shutdown the server, since Max and I agree it would be better to just have a channel in the official Playwright slack. https://join.slack.com/t/playwright/shared_invite/enQtOTEyMTUxMzgxMjIwLThjMDUxZmIyNTRiMTJjNjIyMzdmZDA3MTQxZWUwZTFjZjQwNGYxZGM5MzRmNzZlMWI5ZWUyOTkzMjE5Njg1NDg

**Comment by jperl** [comment]
Closing this issue -- we can discuss more in slack 👍
