### ISSUE TITLE
Add a coverage visualisation tool

### ISSUE THREAD

**Issue by mxschmitt** [mmarkelov/jest-playwright#45]
Like:
- https://codecov.io
- https://coveralls.io

what do you think? I prefer codecov. Very trivial to add, I can take over that issue if you want.

**Comment by mmarkelov** [comment]
@mxschmitt I used **coveralls**, but if **codecov** trivial to add, we can use it

**Comment by mxschmitt** [comment]
Okay, let's use coveralls, so I also use something else. 👍seems to be more popular.

**Comment by mmarkelov** [comment]
Close it with #47
