### ISSUE TITLE
[Bug] Can't connect to WebKit more than once

### ISSUE THREAD

**Issue by pavelfeldman** [mmarkelov/jest-playwright#5]
Cross-referencing https://github.com/microsoft/playwright/issues/830

jest-playwright launches a browser once and then connects to it over webSocket for each environment. That works for Chromium and Firefox since they support multiple web socket clients, but fails for WebKit. I guess we did not do a great job explaining our launcherApp apis and limitations.

What our local harness does instead is running an instance of a browser app per test process. It uses regular playwright.launch for that and then exposes browser.newContext with test environment. @mmarkelov is this something you could do in jest-playwright?

**Comment by FezVrasta** [comment]
Would `--runInBand` help with this issue meanwhile?

**Comment by FezVrasta** [comment]
I still have this problem with the latest version

https://github.com/popperjs/popper-core/pull/990/checks?check_run_id=443616697#step:7:21
