### ISSUE TITLE
Failing tests return exit code 0 instead of 1

### ISSUE THREAD

**Issue by JakeStevenson** [mmarkelov/jest-playwright#55]
I set up a failing jest test.   I observed the following behavior:

> >./node_modules/.bin/jest
> --- TEST RUN ---
> >echo $?
> 1

When run with jest-playwright:
> >./node_modules/.bin/jest-playwright
> --- TEST RUN ---
> >echo $?
> 0

This makes usage of jest-playwright in a CI system difficult.

**Comment by mxschmitt** [comment]
I'm on it, will take a look tomorrow
