### ISSUE TITLE
Feature: add utility expect methods in Jest

### ISSUE THREAD

**Issue by mmarkelov** [mmarkelov/jest-playwright#75]
Support features like **jest-puppeteer**: https://github.com/smooth-code/jest-puppeteer/blob/master/packages/expect-puppeteer/README.md#api

**Comment by mxschmitt** [comment]
I thought about:
- comparing the amount of items of an elector `expect(page).toHaveOccurrences("ul > li", 5)`
- comparing text `expect(page).toHaveInnerText("#ias", "foobar")`
- contains text `expect(page).toContainText("#323", "bar")`

not sure whats actually most useful.

**Comment by mxschmitt** [comment]
I've created a package for that https://github.com/mxschmitt/expect-playwright feel free to contribute to so we can add more utility functions to it.

**Comment by mmarkelov** [comment]
@mxschmitt may be **jest-playwright** should include your package underhood?
