### ISSUE TITLE
Feature: Add jest-playwright as an ESLint environment

### ISSUE THREAD

**Issue by thernstig** [mmarkelov/jest-playwright#80]
https://eslint.org/docs/user-guide/configuring#specifying-environments has a way to configure environments. It would be cool if jest-playwright was part of that, but I am not sure how feasible that is. This would avoid having to specify the globals that come with jest-playwright.

Maybe not worth it and then you can close this, but I just thought I'd bring up the idea even how minor it might be.

**Comment by mmarkelov** [comment]
@thernstig that's make sense

**Comment by mxschmitt** [comment]
@thernstig could you try https://github.com/mxschmitt/eslint-plugin-jest-playwright?
Should fit for your needs, if yes then we can refer to this in the README.

**Comment by thernstig** [comment]
@mxschmitt I verified that it works. A question though. The implementation has this:

```javascript
module.exports = {
  configs: {
    recommended: {
      env: {
        node: true,
        jest: true,
      },
      globals: {
        browser: true,
        context: true,
        page: true,
        jestPlaywright: true,
      }
    }
  },
}
```

Isn't this more proper?

```javascript
module.exports = {
  configs: {
    recommended: {
      env: {
        shared-node-browser: true,
        jest: true,
      },
      globals: {
        browser: true,
        context: true,
        page: true,
        jestPlaywright: true,
      }
    }
  },
}
```

Reason being that you can just `document.` in many of the Playwright functions that runs inside the browser.

**Comment by mxschmitt** [comment]
> @mxschmitt I verified that it works. A question though. The implementation has this:
> 
> ```js
> module.exports = {
>   configs: {
>     recommended: {
>       env: {
>         node: true,
>         jest: true,
>       },
>       globals: {
>         browser: true,
>         context: true,
>         page: true,
>         jestPlaywright: true,
>       }
>     }
>   },
> }
> ```
> 
> Isn't this more proper?
> 
> ```js
> module.exports = {
>   configs: {
>     recommended: {
>       env: {
>         shared-node-browser: true,
>         jest: true,
>       },
>       globals: {
>         browser: true,
>         context: true,
>         page: true,
>         jestPlaywright: true,
>       }
>     }
>   },
> }
> ```
> 
> Reason being that you can just `document.` in many of the Playwright functions that runs inside the browser.

good catch, will adjust this in a bit! :)
